name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -scheme Tracer \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -skipPackagePluginValidation \
            build
